name: Update ZIP code market Data

permissions:
  contents: write
  issues: write

on:
  schedule:
    - cron: '0 0 26 * *' # Runs at 00:00 UTC on the 26st of every month
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests

    - name: Run Redfin Data Pipeline
      run: |
        python -u scripts/update-market-data.py

    - name: Display Logs
      if: always() 
      run: |
        echo "--- Displaying contents of data_pipeline.log ---"
        cat data_pipeline.log
        echo "--- End of log ---"

    - name: Check for changes in data
      id: check_changes
      run: |
        if [ ! -f public/data/last_updated.json ]; then
          echo "last_updated.json not found â€” assume changes"
          echo "changes=true" >> $GITHUB_OUTPUT
          exit 0
        fi

        DATA_POINTS_CHANGED=$(jq '.data_points_changed' public/data/last_updated.json)

        if [ "$DATA_POINTS_CHANGED" -gt 0 ]; then
          echo "Data points changed: $DATA_POINTS_CHANGED"
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "No data point changes"
          echo "changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Commit and push if changed
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/data/zip-data.json public/data/last_updated.json
        git commit -m "Update Redfin ZIP data - $(date +'%Y-%m-%d %H:%M:%S' --utc)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create issue if failed
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Redfin Data Update Failed',
            body: `The automated Redfin data update failed on ${new Date().toISOString()}.

            Please check the workflow logs for details.

            Auto-generated by GitHub Actions.`
          })
